version: '3.2'
services:
  status_bot:
    container_name: cryptic-status-bot
    image: defelo/cryptic-status-bot:latest
    restart: always
    tty: true
    volumes:
      - ./config.json:/app/config.json:ro
    environment:
      TOKEN: '[TOKEN]'
